// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cigkcvkhujjadboowrxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZ2tjdmtodWpqYWRib293cnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MzcxMDgsImV4cCI6MjA2MzAxMzEwOH0.eKA3YPPqZiN0eAmXgOfnxuUzVRtkaAmAri0uZnWlBDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);